[package]
name = "vulkano-win"
version = "0.3.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
repository = "https://github.com/tomaka/vulkano"
description = "Link between vulkano and winit"
license = "MIT/Apache-2.0"

[dependencies]
vulkano = { version = "0.3.0", path = "../vulkano" }
winit = "0.5.6"
